apiVersion: skaffold/v4beta13
kind: Config

manifests:
  rawYaml:
    - ./infra/k8s/*

build:
  local:
    push: false
  artifacts:
    - image: book-service
      context: book-service
      docker:
        dockerfile: Dockerfile
    - image: post-service
      context: post-service
      docker:
        dockerfile: Dockerfile
    - image: order-service
      context: order-service
      docker:
        dockerfile: Dockerfile
    - image: member-service
      context: member-service
      docker:
        dockerfile: Dockerfile
    - image: message-service
      context: message-service
      docker:
        dockerfile: Dockerfile

deploy:
  helm:
    releases:
      - name: kafka
        remoteChart: kafka
        repo: https://charts.bitnami.com/bitnami
        setValues:
          replicaCount: "3"
          listeners:
            client:
              protocol: plaintext
            controllers:
              protocol: plaintext
            interbroker:
              protocol: plaintext


portForward:
  - resourceType: service
    resourceName: book-service-srv
    port: 8081
    localPort: 8081
  - resourceType: service
    resourceName: member-service-srv
    port: 8087
    localPort: 8087