apiVersion: skaffold/v4beta13
kind: Config

manifests:
  rawYaml:
    - ./infra/k8s/*
#    - ./infra/k8s/ingress-depl.yml
#    - ./infra/k8s/message-service-depl.yml

profiles:
  - name: prod
    build:
      artifacts: []
    deploy:
      helm:
        releases:
          - name: kafka
            remoteChart: kafka
            repo: https://charts.bitnami.com/bitnami
            setValues:
              controller:
                replicaCount: 1
              listeners:
                client:
                  protocol: plaintext
                controllers:
                  protocol: plaintext
                interbroker:
                  protocol: plaintext


#portForward:
#  - resourceType: service
#    resourceName: book-service-srv
#    port: 8081
#    localPort: 8081
#  - resourceType: service
#    resourceName: member-service-srv
#    port: 8087
#    localPort: 8087

