apiVersion: skaffold/v4beta13
kind: Config

manifests:
  rawYaml:
    - ./infra/k8s/ingress-traefik-depl.yml
    - ./infra/k8s/echo-depl.yml
    - ./infra/k8s/book-service-depl.yml
    - ./infra/k8s/post-service-depl.yml
    - ./infra/k8s/order-service-depl.yml
    - ./infra/k8s/member-service-depl.yml
    - ./infra/k8s/message-service-depl.yml

profiles:
  - name: prod
    build:
      artifacts: []
    deploy:
      helm:
        releases:
          - name: kafka
            remoteChart: kafka
            repo: oci://registry-1.docker.io/bitnamicharts/kafka #bitnami no longer free -> use legacy one
            version: 32.4.3
            setValues:
              image.registry: docker.io
              image.repository: bitnamilegacy/kafka
              image.tags: 4.0.0-debian-12-r10
              controller:
                replicaCount: 3
              listeners:
                client:
                  protocol: plaintext
                controller:
                  protocol: plaintext
                interbroker:
                  protocol: plaintext
