server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: "localhost:9092,localhost:9093,localhost:9094"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery-timeout-ms: 120000
        linger-ms: 0
        request-timeout-ms: 30000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: "book-service-group"
      properties:
        spring.json.trusted.packages: "com.goodmanltd.*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-fgn67tyj1m63t283.us.auth0.com/
          jwk-set-uri: https://dev-fgn67tyj1m63t283.us.auth0.com/.well-known/jwks.json
          audiences:
            - https://bookcrossing.goodmanltd.com
  profiles:
    active: mongo


app:
  kafka:
    topics:
      bookCreated: book-created-events-topic
      bookUpdated: book-updated-events-topic

auth0:
  audience: https://bookcrossing.goodmanltd.com

google:
  apiKey: "AIzaSyDOxU-SuS-qyeN4yeIgT7HIyoD0Q-pLCl0"