apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service
          ports:
            - containerPort: 8083
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
                  key: MONGO_URI
            - name: AUTH0_ISSUER
              valueFrom:
                secretKeyRef:
                  name: auth0-issuer
                  key: AUTH0_ISSUER
            - name: JWT_SET_URI
              valueFrom:
                secretKeyRef:
                  name: jwt-set-uri
                  key: JWT_SET_URI
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-api-key
                  key: GOOGLE_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-srv
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - name: order-service
      protocol: TCP
      port: 8083
      targetPort: 8083